### ISSUE TITLE
Genomelist to .ped fails

### ISSUE THREAD

**Issue by timknut** [haraldgrove/snptranslate#4]
I have an illumina finalreport fileset. It is in the Genomelist format. (I guess)
```
[Header]
GSGT Version    1.9.4
Processing Date 4/27/2016 4:28 PM
Content         SheepHD_AgResearch_Cons_15041608_A.bpm
Num SNPs        606006
Total SNPs      606006
Num Samples     189
Total Samples   197
[Data]
SNP Name        Sample ID       Allele1 - AB    Allele2 - AB    X       Y       GC Score
tikn@login-0:~/for_folk/DagInge/dagiva_sheep700chip$ head -15  JCM2880_NOR_All_FinalReport.txt
[Header]
GSGT Version    1.9.4
Processing Date 4/27/2016 4:28 PM
Content         SheepHD_AgResearch_Cons_15041608_A.bpm
Num SNPs        606006
Total SNPs      606006
Num Samples     189
Total Samples   197
[Data]
SNP Name        Sample ID       Allele1 - AB    Allele2 - AB    X       Y       GC Score
250506CS3900140500001_312.1     JC2879_A01_BB776135     A       B       0.631   0.637   0.9403
250506CS3900176800001_906.1     JC2879_A01_BB776135     B       B       0.023   0.849   0.9288
250506CS3900211600001_1041.1    JC2879_A01_BB776135     B       B       0.036   0.959   0.9250
250506CS3900218700001_1294.1    JC2879_A01_BB776135     A       A       0.588   0.082   0.8089
250506CS3900283200001_442.1     JC2879_A01_BB776135     B       B       0.036   0.806   0.9347
```

the marker file for the -m argument:
 ```
23      250506CS3900140500001_312.1     0       26298017        T       C
7       250506CS3900176800001_906.1     0       81648528        T       C
16      250506CS3900211600001_1041.1    0       41355381        T       G
2       250506CS3900218700001_1294.1    0       148802744       T       C
```

The opSNP.py command:
```
python /mnt/users/tikn/bioinf_tools/snptranslate/ioSNP.py -i JCM2880_NOR_All_FinalReport.txt -n Genomelist -o JCM2880_NOR_All_FinalReport.ped -u Plink -m markerfile.map"
```

Failes with:
```
cat slurm-1688578.out
Traceback (most recent call last):
  File "/mnt/users/tikn/bioinf_tools/snptranslate/ioSNP.py", line 168, in <module>
    main()
  File "/mnt/users/tikn/bioinf_tools/snptranslate/ioSNP.py", line 161, in main
    genos = gen1.readFile(args.input,rmark)
  File "/mnt/users/tikn/bioinf_tools/snptranslate/iomods/ioGenomelist.py", line 96, in readFile
    animal = l[csample]
IndexError: list index out of range
```

Any clues? 

Tim

**Comment by haraldgrove** [comment]
Something as simple as forgetting to check if the line just read is empty (or contains too few elements). Should be fixed now.
