### ISSUE TITLE
Remove the duplicate samples exception or just warn. 

### ISSUE THREAD

**Issue by timknut** [haraldgrove/snptranslate#9]
Unsure if I can do this myself, but think it is a good idea to just warn, because in many cases the same sample is genotyped several times, or you want to convert concatenated files. 

```
Traceback (most recent call last):
  File "/mnt/users/tikn/for_folk/geno/geno_imputation/scripts/snptranslate/ioSNP.py", line 168, in <module>
    main()
  File "/mnt/users/tikn/for_folk/geno/geno_imputation/scripts/snptranslate/ioSNP.py", line 161, in main
    genos = gen1.readFile(args.input,rmark)
  File "/mnt/users/tikn/for_folk/geno/geno_imputation/scripts/snptranslate/iomods/ioGenomematrix.py", line 70, in readFile
    ped,mark = self.updatePedMark(input)
  File "/mnt/users/tikn/for_folk/geno/geno_imputation/scripts/snptranslate/iomods/ioGenomematrix.py", line 50, in updatePedMark
    raise Exception('Duplicate samples')
Exception: Duplicate samples

```

**Comment by haraldgrove** [comment]
Ah, well. The problem is that I think most (if not all) of the program is working on the assumption that sample names are unique. So it depends on whether you're suggesting to merge identical samples or keep them separate and write out both versions.

I don't think it's particularly complicated, but it will most likely take some time to make sure you don't break anything else in the process.

**Comment by timknut** [comment]
For me and Geno, keeping them separate is convenient. But I can ask Arne
about a pull request. Can eg. make a branch.
1. nov. 2016 13.33 skrev "Harald Grove" notifications@github.com:

Ah, well. The problem is that I think most (if not all) of the program is
working on the assumption that sample names are unique. So it depends on
whether you're suggesting to merge identical samples or keep them separate
and write out both versions.

I don't think it's particularly complicated, but it will most likely take
some time to make sure you don't break anything else in the process.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/haraldgrove/snptranslate/issues/9#issuecomment-260119619,
or mute the thread

**Comment by haraldgrove** [comment]
If you want to keep the samples separate, why not make the IDs unique? You can store the different versions in the main database, and when you want to use the animal in an analysis you merge them together based on some criteria. I don't see any benefit of keeping them separate for anything else, unless I'm missing something?
